// Complete Realistic Mock Data for Vercel Cloud Preview & Local Fallback
export const mockCategories = [
  { category_id: 1, category_name: 'ID Card & Credentials', icon: 'BadgeCheck', description: 'College RFID identity cards, bus passes, and hall tickets' },
  { category_id: 2, category_name: 'Smartphone & Accessories', icon: 'Smartphone', description: 'Smartphones, charging adapters, cables, and power banks' },
  { category_id: 3, category_name: 'Laptop & Computing', icon: 'Laptop', description: 'Laptops, tablets, hard drives, flash drives, and mouse' },
  { category_id: 4, category_name: 'Wallet & Currency', icon: 'Wallet', description: 'Wallets, purses, pouches, debit cards, and cash clips' },
  { category_id: 5, category_name: 'Keys & Access Cards', icon: 'Key', description: 'Room keys, hostel keys, vehicle ignition keys, and fobs' },
  { category_id: 6, category_name: 'Books & Study Material', icon: 'BookOpen', description: 'Textbooks, lab observation notebooks, drawing sheets, calculators' },
  { category_id: 7, category_name: 'Audio & Headphones', icon: 'Headphones', description: 'Earphones, wireless earbuds, charging cases, and neckbands' },
  { category_id: 8, category_name: 'Water Bottle & Tumbler', icon: 'CupSoda', description: 'Insulated bottles, steel flasks, gym shakers, and tumblers' },
  { category_id: 9, category_name: 'Watch & Wearable', icon: 'Watch', description: 'Analog wristwatches, smart fitness bands, and chronographs' },
  { category_id: 10, category_name: 'Eyewear & Sunglasses', icon: 'Glasses', description: 'Prescription spectacles, anti-glare glasses, and sunglasses' }
];

export const mockLocations = [
  { location_id: 1, location_name: 'Central Library - 1st Floor Reading Hall', building: 'Central Library', floor_zone: 'First Floor, Wing A' },
  { location_id: 2, location_name: 'Main Academic Block - Room 302', building: 'Main Academic Block', floor_zone: 'Third Floor' },
  { location_id: 3, location_name: 'Engineering Lab Block - IoT Lab', building: 'Lab Complex', floor_zone: 'Second Floor, West Wing' },
  { location_id: 4, location_name: 'Student Activity Center - Food Court', building: 'Student Amenities Center', floor_zone: 'Ground Floor' },
  { location_id: 5, location_name: 'Campus Sports Complex - Badminton Court', building: 'Indoor Stadium', floor_zone: 'Courts Area' },
  { location_id: 6, location_name: 'Central Auditorium - Ground Floor Foyer', building: 'University Auditorium', floor_zone: 'Ground Floor' },
  { location_id: 7, location_name: 'Mechanical Workshop - Bay 2', building: 'Mechanical Block', floor_zone: 'Ground Floor' },
  { location_id: 8, location_name: 'South Academic Block - Room 108', building: 'South Academic Block', floor_zone: 'First Floor' },
  { location_id: 9, location_name: 'Computing Block - Lab 4', building: 'Computing Block', floor_zone: 'Second Floor' },
  { location_id: 10, location_name: 'Campus Bus Terminus - Bay 3', building: 'Transport Depot', floor_zone: 'Open Terminal' }
];

export const mockStudentUser = {
  student_id: 2,
  reg_no: 'AM.EN.U4CSE23012',
  full_name: 'Mohul Ramjee',
  email: 'student@campustrack.edu',
  phone: '+91 63817 61164',
  department: 'Computer Science and Engineering',
  role: 'student'
};

export const mockAdminUser = {
  student_id: 1,
  reg_no: 'ADMIN-001',
  full_name: 'Chief Campus Administrator',
  email: 'admin@campustrack.edu',
  phone: '+91 98401 23456',
  department: 'Campus Security & Welfare',
  role: 'admin'
};

export const mockLostItems = [
  {
    lost_id: 1,
    student_id: 2,
    category_id: 4,
    category_name: 'Wallet & Currency',
    location_id: 1,
    location_name: 'Central Library - 1st Floor Reading Hall',
    building: 'Central Library',
    item_name: 'Black Leather Fossil Wallet',
    brand: 'Fossil',
    primary_color: 'Black',
    date_lost: '2026-09-08',
    approx_time: '14:30:00',
    description: 'Bi-fold dark brown/black leather wallet with currency compartment and RFID blocking lining',
    identifying_details: 'Contains student ID card ending in 23012, SBI debit card, and passport-size photo inside clear sleeve',
    status: 'Matched',
    match_count: 1,
    reported_by: 'Mohul Ramjee',
    department: 'Computer Science and Engineering',
    created_at: '2026-09-08T14:30:00Z'
  },
  {
    lost_id: 2,
    student_id: 3,
    category_id: 2,
    category_name: 'Smartphone & Accessories',
    location_id: 2,
    location_name: 'Main Academic Block - Room 302',
    building: 'Main Academic Block',
    item_name: 'iPhone 13 Midnight Blue 128GB',
    brand: 'Apple',
    primary_color: 'Blue',
    date_lost: '2026-09-09',
    approx_time: '11:15:00',
    description: 'Apple iPhone 13 with matte black silicone bumper case and tempered glass screen protector',
    identifying_details: 'Lock screen has photo of a golden retriever puppy; transparent sticker of GitHub octocat on back',
    status: 'Matched',
    match_count: 1,
    reported_by: 'Aarav Sharma',
    department: 'Computer Science and Engineering',
    created_at: '2026-09-09T11:15:00Z'
  },
  {
    lost_id: 3,
    student_id: 2,
    category_id: 1,
    category_name: 'ID Card & Credentials',
    location_id: 4,
    location_name: 'Student Activity Center - Food Court',
    building: 'Student Amenities Center',
    item_name: 'Student ID Card & Amrita Smart Card',
    brand: 'Campus Card',
    primary_color: 'Blue',
    date_lost: '2026-09-10',
    approx_time: '13:00:00',
    description: 'Campus student identification card on navy blue neck lanyard with plastic card sleeve',
    identifying_details: 'Registration number AM.EN.U4CSE23012 with library barcode on reverse side',
    status: 'Matched',
    match_count: 1,
    reported_by: 'Mohul Ramjee',
    department: 'Computer Science and Engineering',
    created_at: '2026-09-10T13:00:00Z'
  },
  {
    lost_id: 4,
    student_id: 4,
    category_id: 7,
    category_name: 'Audio & Headphones',
    location_id: 3,
    location_name: 'Engineering Lab Block - IoT Lab',
    building: 'Lab Complex',
    item_name: 'Boat Airdopes 141 Wireless Earbuds',
    brand: 'Boat',
    primary_color: 'Black',
    date_lost: '2026-09-07',
    approx_time: '16:45:00',
    description: 'True wireless earbuds in compact matte black charging case with LED battery indicator',
    identifying_details: 'Small scratch on right earbud body; silicone tips are size M',
    status: 'Matched',
    match_count: 1,
    reported_by: 'Ananya Iyer',
    department: 'Electronics and Communication',
    created_at: '2026-09-07T16:45:00Z'
  },
  {
    lost_id: 5,
    student_id: 5,
    category_id: 9,
    category_name: 'Watch & Wearable',
    location_id: 5,
    location_name: 'Campus Sports Complex - Badminton Court',
    building: 'Indoor Stadium',
    item_name: 'Fastrack Reflex Play Smartwatch',
    brand: 'Fastrack',
    primary_color: 'Black',
    date_lost: '2026-09-06',
    approx_time: '18:00:00',
    description: 'Black dial touchscreen fitness smartwatch with textured black silicone strap',
    identifying_details: 'Metal buckle has slight scratch; watch face is set to digital neon orange clock',
    status: 'Matched',
    match_count: 1,
    reported_by: 'Rohan Verma',
    department: 'Artificial Intelligence & Data Science',
    created_at: '2026-09-06T18:00:00Z'
  },
  {
    lost_id: 6,
    student_id: 6,
    category_id: 6,
    category_name: 'Books & Study Material',
    location_id: 8,
    location_name: 'South Academic Block - Room 108',
    building: 'South Academic Block',
    item_name: 'Casio FX-991CW Scientific Calculator',
    brand: 'Casio',
    primary_color: 'Black',
    date_lost: '2026-09-08',
    approx_time: '09:30:00',
    description: 'ClassWiz advanced scientific calculator with white sliding protective cover',
    identifying_details: 'Small silver sticker with initials D.N. taped inside the protective cover',
    status: 'Matched',
    match_count: 1,
    reported_by: 'Divya Nair',
    department: 'Mechanical Engineering',
    created_at: '2026-09-08T09:30:00Z'
  },
  {
    lost_id: 7,
    student_id: 7,
    category_id: 8,
    category_name: 'Water Bottle & Tumbler',
    location_id: 1,
    location_name: 'Central Library - 1st Floor Reading Hall',
    building: 'Central Library',
    item_name: 'Milton ThermoSteel Flip Lid Flask 1L',
    brand: 'Milton',
    primary_color: 'Silver',
    date_lost: '2026-09-09',
    approx_time: '15:20:00',
    description: 'Double walled vacuum insulated stainless steel water flask with push button sip cap',
    identifying_details: 'Dent on the bottom steel rim; red sports strap attached around the neck',
    status: 'Lost',
    match_count: 0,
    reported_by: 'Karthik Raj',
    department: 'Computer Science and Engineering',
    created_at: '2026-09-09T15:20:00Z'
  },
  {
    lost_id: 8,
    student_id: 8,
    category_id: 5,
    category_name: 'Keys & Access Cards',
    location_id: 4,
    location_name: 'Student Activity Center - Food Court',
    building: 'Student Amenities Center',
    item_name: 'Honda Activa Key with Iron Man Keychain',
    brand: 'Honda',
    primary_color: 'Silver',
    date_lost: '2026-09-09',
    approx_time: '12:40:00',
    description: 'Single scooter ignition key with red and gold metallic Iron Man miniature helmet',
    identifying_details: 'Black plastic key grip with engraved code H-492',
    status: 'Lost',
    match_count: 0,
    reported_by: 'Sneha Patel',
    department: 'Electrical and Electronics',
    created_at: '2026-09-09T12:40:00Z'
  },
  {
    lost_id: 9,
    student_id: 9,
    category_id: 3,
    category_name: 'Laptop & Computing',
    location_id: 9,
    location_name: 'Computing Block - Lab 4',
    building: 'Computing Block',
    item_name: 'Dell 65W Type-C Laptop Power Adapter',
    brand: 'Dell',
    primary_color: 'Black',
    date_lost: '2026-09-05',
    approx_time: '17:10:00',
    description: 'Black charging brick with USB-C cable and 3-pin Indian wall plug',
    identifying_details: 'White velcro cable tie wrapped around the middle of the long cord',
    status: 'Claimed',
    match_count: 1,
    reported_by: 'Rahul Menon',
    department: 'Computer Science and Engineering',
    created_at: '2026-09-05T17:10:00Z'
  },
  {
    lost_id: 10,
    student_id: 10,
    category_id: 10,
    category_name: 'Eyewear & Sunglasses',
    location_id: 1,
    location_name: 'Central Library - 1st Floor Reading Hall',
    building: 'Central Library',
    item_name: 'Ray-Ban Wayfarer Classic Glasses',
    brand: 'Ray-Ban',
    primary_color: 'Brown',
    date_lost: '2026-09-04',
    approx_time: '14:00:00',
    description: 'Dark tortoise shell optical frame with anti-reflective blue-light filter prescription lenses',
    identifying_details: 'Model RB2140 engraved on inside of left temple',
    status: 'Closed',
    match_count: 1,
    reported_by: 'Priya Sundaram',
    department: 'Electronics and Communication',
    created_at: '2026-09-04T14:00:00Z'
  }
];

export const mockFoundItems = [
  {
    found_id: 1,
    student_id: 7,
    category_id: 4,
    category_name: 'Wallet & Currency',
    location_id: 1,
    location_name: 'Central Library - 1st Floor Reading Hall',
    building: 'Central Library',
    item_name: 'Black Leather Fossil Wallet',
    brand: 'Fossil',
    primary_color: 'Black',
    date_found: '2026-09-08',
    approx_time: '15:00:00',
    description: 'Found on study desk 14 in Central Library reading hall; black bi-fold leather wallet',
    identifying_details: 'Cards verified inside wallet; held in security register #L-401',
    storage_location: 'Central Library Security Counter',
    status: 'Matched',
    reported_by: 'Karthik Raj',
    created_at: '2026-09-08T15:00:00Z'
  },
  {
    found_id: 2,
    student_id: 8,
    category_id: 2,
    category_name: 'Smartphone & Accessories',
    location_id: 2,
    location_name: 'Main Academic Block - Room 302',
    building: 'Main Academic Block',
    item_name: 'iPhone 13 Dark Blue with Black Case',
    brand: 'Apple',
    primary_color: 'Blue',
    date_found: '2026-09-09',
    approx_time: '11:40:00',
    description: 'Recovered from podium drawer in Main Academic Block Room 302 after CSE lecture',
    identifying_details: 'Device powered on, locked with 6-digit passcode',
    storage_location: 'Dean Office Security Locker',
    status: 'Matched',
    reported_by: 'Sneha Patel',
    created_at: '2026-09-09T11:40:00Z'
  },
  {
    found_id: 3,
    student_id: 9,
    category_id: 1,
    category_name: 'ID Card & Credentials',
    location_id: 4,
    location_name: 'Student Activity Center - Food Court',
    building: 'Student Amenities Center',
    item_name: 'Student ID Card (CSE Dept)',
    brand: 'Campus Card',
    primary_color: 'Blue',
    date_found: '2026-09-10',
    approx_time: '13:25:00',
    description: 'Found near tray return counter at Food Court table #9; navy blue lanyard',
    identifying_details: 'Amrita Vishwa Vidyapeetham student smart card',
    storage_location: 'Amenities Center Helpdesk',
    status: 'Matched',
    reported_by: 'Rahul Menon',
    created_at: '2026-09-10T13:25:00Z'
  },
  {
    found_id: 4,
    student_id: 10,
    category_id: 7,
    category_name: 'Audio & Headphones',
    location_id: 3,
    location_name: 'Engineering Lab Block - IoT Lab',
    building: 'Lab Complex',
    item_name: 'Boat Wireless Earbuds Case Black',
    brand: 'Boat',
    primary_color: 'Black',
    date_found: '2026-09-07',
    approx_time: '17:15:00',
    description: 'Found under bench workstation 6 in IoT lab; matte black casing with earbuds inside',
    identifying_details: 'Both earbuds present inside charging dock',
    storage_location: 'IoT Lab Staff Room Cupboard',
    status: 'Matched',
    reported_by: 'Priya Sundaram',
    created_at: '2026-09-07T17:15:00Z'
  },
  {
    found_id: 5,
    student_id: 11,
    category_id: 9,
    category_name: 'Watch & Wearable',
    location_id: 5,
    location_name: 'Campus Sports Complex - Badminton Court',
    building: 'Indoor Stadium',
    item_name: 'Black Touchscreen Smartwatch',
    brand: 'Fastrack',
    primary_color: 'Black',
    date_found: '2026-09-06',
    approx_time: '18:45:00',
    description: 'Found on spectator bench near court 2 after evening badminton session',
    identifying_details: 'Battery was low; charged at sports office',
    storage_location: 'Sports Pavilion Office',
    status: 'Matched',
    reported_by: 'Vikram Aditya',
    created_at: '2026-09-06T18:45:00Z'
  },
  {
    found_id: 6,
    student_id: 12,
    category_id: 6,
    category_name: 'Books & Study Material',
    location_id: 8,
    location_name: 'South Academic Block - Room 108',
    building: 'South Academic Block',
    item_name: 'Casio Scientific Calculator White Cover',
    brand: 'Casio',
    primary_color: 'Black',
    date_found: '2026-09-08',
    approx_time: '10:00:00',
    description: 'Left behind on second-row desk after Tutorial hour',
    identifying_details: 'White cover has faint pencil markings on interior',
    storage_location: 'Mathematics Department Office',
    status: 'Matched',
    reported_by: 'Meera Krishnan',
    created_at: '2026-09-08T10:00:00Z'
  },
  {
    found_id: 7,
    student_id: 13,
    category_id: 8,
    category_name: 'Water Bottle & Tumbler',
    location_id: 1,
    location_name: 'Central Library - 1st Floor Reading Hall',
    building: 'Central Library',
    item_name: 'Stainless Steel Insulated Flask',
    brand: 'Milton',
    primary_color: 'Silver',
    date_found: '2026-09-09',
    approx_time: '16:00:00',
    description: 'Found on water dispenser counter in Library Wing A',
    identifying_details: '1L capacity, push-button lid',
    storage_location: 'Central Library Security Counter',
    status: 'Found',
    reported_by: 'Arjun Reddy',
    created_at: '2026-09-09T16:00:00Z'
  },
  {
    found_id: 8,
    student_id: 14,
    category_id: 5,
    category_name: 'Keys & Access Cards',
    location_id: 4,
    location_name: 'Student Activity Center - Food Court',
    building: 'Student Amenities Center',
    item_name: 'Two-Wheeler Ignition Key with Superhero Toy',
    brand: 'Honda',
    primary_color: 'Silver',
    date_found: '2026-09-09',
    approx_time: '13:10:00',
    description: 'Handed over by cleaning staff from table near Nescafe stall',
    identifying_details: 'Metallic superhero head keychain attached with small chain',
    storage_location: 'Campus Security Main Gate Station',
    status: 'Found',
    reported_by: 'Pooja Hegde',
    created_at: '2026-09-09T13:10:00Z'
  },
  {
    found_id: 9,
    student_id: 15,
    category_id: 3,
    category_name: 'Laptop & Computing',
    location_id: 9,
    location_name: 'Computing Block - Lab 4',
    building: 'Computing Block',
    item_name: 'Dell 65 Watt USB Type-C Charger',
    brand: 'Dell',
    primary_color: 'Black',
    date_found: '2026-09-05',
    approx_time: '17:40:00',
    description: 'Plugged in wall socket at workstation row 3 in Computing Lab',
    identifying_details: 'Clean adapter with cable tie; original Dell serial',
    storage_location: 'Computing Block Lab In-Charge Desk',
    status: 'Claimed',
    reported_by: 'Siddharth Roy',
    created_at: '2026-09-05T17:40:00Z'
  },
  {
    found_id: 10,
    student_id: 16,
    category_id: 10,
    category_name: 'Eyewear & Sunglasses',
    location_id: 1,
    location_name: 'Central Library - 1st Floor Reading Hall',
    building: 'Central Library',
    item_name: 'Prescription Spectacles in Hard Case',
    brand: 'Ray-Ban',
    primary_color: 'Brown',
    date_found: '2026-09-04',
    approx_time: '14:30:00',
    description: 'Found inside black leather zip case on newspaper reading table',
    identifying_details: 'Dark tortoise frame, verified with security slip',
    storage_location: 'Central Library Security Counter',
    status: 'Closed',
    reported_by: 'Tanvi Joshi',
    created_at: '2026-09-04T14:30:00Z'
  }
];

export const mockMatches = [
  {
    match_id: 1,
    score: 100,
    match_status: 'Suggested',
    created_at: '2026-09-08T15:30:00Z',
    lost_id: 1,
    lost_name: 'Black Leather Fossil Wallet',
    lost_brand: 'Fossil',
    lost_color: 'Black',
    lost_status: 'Matched',
    lost_by_name: 'Mohul Ramjee',
    found_id: 1,
    found_name: 'Black Leather Fossil Wallet',
    found_brand: 'Fossil',
    found_color: 'Black',
    found_status: 'Matched',
    found_by_name: 'Karthik Raj',
    storage_location: 'Central Library Security Counter',
    category_name: 'Wallet & Currency',
    lost_location_name: 'Central Library - 1st Floor Reading Hall',
    found_location_name: 'Central Library - 1st Floor Reading Hall',
    score_breakdown: {
      category_score: 25,
      location_score: 25,
      color_score: 15,
      brand_score: 15,
      description_score: 10,
      date_score: 10,
      total_score: 100
    }
  },
  {
    match_id: 2,
    score: 95,
    match_status: 'Suggested',
    created_at: '2026-09-09T12:00:00Z',
    lost_id: 2,
    lost_name: 'iPhone 13 Midnight Blue 128GB',
    lost_brand: 'Apple',
    lost_color: 'Blue',
    lost_status: 'Matched',
    lost_by_name: 'Aarav Sharma',
    found_id: 2,
    found_name: 'iPhone 13 Dark Blue with Black Case',
    found_brand: 'Apple',
    found_color: 'Blue',
    found_status: 'Matched',
    found_by_name: 'Sneha Patel',
    storage_location: 'Dean Office Security Locker',
    category_name: 'Smartphone & Accessories',
    lost_location_name: 'Main Academic Block - Room 302',
    found_location_name: 'Main Academic Block - Room 302',
    score_breakdown: {
      category_score: 25,
      location_score: 25,
      color_score: 15,
      brand_score: 15,
      description_score: 8,
      date_score: 7,
      total_score: 95
    }
  },
  {
    match_id: 3,
    score: 90,
    match_status: 'Suggested',
    created_at: '2026-09-10T14:00:00Z',
    lost_id: 3,
    lost_name: 'Student ID Card & Amrita Smart Card',
    lost_brand: 'Campus Card',
    lost_color: 'Blue',
    lost_status: 'Matched',
    lost_by_name: 'Mohul Ramjee',
    found_id: 3,
    found_name: 'Student ID Card (CSE Dept)',
    found_brand: 'Campus Card',
    found_color: 'Blue',
    found_status: 'Matched',
    found_by_name: 'Rahul Menon',
    storage_location: 'Amenities Center Helpdesk',
    category_name: 'ID Card & Credentials',
    lost_location_name: 'Student Activity Center - Food Court',
    found_location_name: 'Student Activity Center - Food Court',
    score_breakdown: {
      category_score: 25,
      location_score: 25,
      color_score: 15,
      brand_score: 15,
      description_score: 5,
      date_score: 5,
      total_score: 90
    }
  }
];

export const mockClaims = [
  {
    claim_id: 1,
    match_id: 1,
    lost_id: 1,
    found_id: 1,
    claimant_id: 2,
    claimant_name: 'Mohul Ramjee',
    claimant_email: 'student@campustrack.edu',
    claimant_reg_no: 'AM.EN.U4CSE23012',
    claimant_department: 'Computer Science and Engineering',
    lost_name: 'Black Leather Fossil Wallet',
    found_name: 'Black Leather Fossil Wallet',
    storage_location: 'Central Library Security Counter',
    category_name: 'Wallet & Currency',
    location_name: 'Central Library - 1st Floor Reading Hall',
    claim_description: 'I left my black Fossil bi-fold wallet on reading desk 14 while studying yesterday.',
    identifying_marks: 'Contains my Amrita student ID card AM.EN.U4CSE23012 and SBI global debit card.',
    proof_details: 'Can present registration receipt and government Aadhaar card to security desk.',
    claim_status: 'Pending',
    admin_remarks: null,
    created_at: '2026-09-08T16:00:00Z'
  }
];

export const mockDashboard = {
  kpis: {
    totalStudents: 17,
    totalLost: 20,
    totalFound: 20,
    pendingMatches: 8,
    pendingClaims: 4,
    returnedItems: 6,
    resolutionRate: 30
  },
  charts: {
    categoryDistribution: [
      { category_name: 'Smartphone & Accessories', lost_count: 5, found_count: 5 },
      { category_name: 'Wallet & Currency', lost_count: 4, found_count: 4 },
      { category_name: 'ID Card & Credentials', lost_count: 4, found_count: 4 },
      { category_name: 'Laptop & Computing', lost_count: 3, found_count: 3 },
      { category_name: 'Keys & Access Cards', lost_count: 3, found_count: 3 },
      { category_name: 'Water Bottle & Tumbler', lost_count: 2, found_count: 2 }
    ],
    locationDistribution: [
      { location_name: 'Central Library', building: 'Central Library', lost_count: 6, found_count: 6 },
      { location_name: 'Student Activity Center', building: 'Amenities Center', lost_count: 5, found_count: 5 },
      { location_name: 'Main Academic Block', building: 'Main Academic Block', lost_count: 4, found_count: 4 },
      { location_name: 'Engineering Lab Block', building: 'Lab Complex', lost_count: 3, found_count: 3 },
      { location_name: 'Sports Complex', building: 'Indoor Stadium', lost_count: 2, found_count: 2 }
    ],
    statusDistribution: [
      { status: 'Lost', count: 14 },
      { status: 'Found', count: 14 },
      { status: 'Matched', count: 8 },
      { status: 'Claimed', count: 4 }
    ]
  },
  recentActivity: [
    { type: 'CLAIM', id: 1, title: 'Claim on: Black Leather Fossil Wallet', status: 'Pending', person: 'Mohul Ramjee', created_at: '2026-09-08T16:00:00Z' },
    { type: 'FOUND', id: 3, title: 'Student ID Card (CSE Dept)', status: 'Matched', person: 'Rahul Menon', created_at: '2026-09-10T13:25:00Z' },
    { type: 'LOST', id: 3, title: 'Student ID Card & Amrita Smart Card', status: 'Matched', person: 'Mohul Ramjee', created_at: '2026-09-10T13:00:00Z' },
    { type: 'FOUND', id: 2, title: 'iPhone 13 Dark Blue with Black Case', status: 'Matched', person: 'Sneha Patel', created_at: '2026-09-09T11:40:00Z' },
    { type: 'LOST', id: 2, title: 'iPhone 13 Midnight Blue 128GB', status: 'Matched', person: 'Aarav Sharma', created_at: '2026-09-09T11:15:00Z' }
  ]
};

export const mockAuditLogs = [
  { log_id: 1, entity_type: 'CLAIM', entity_id: 1, old_status: 'Pending', new_status: 'Approved', changer_name: 'Chief Campus Administrator', changer_role: 'admin', change_notes: 'Claim verified via ACID transaction. Physical wallet custody matched student ID.', timestamp: '2026-09-08T17:00:00Z' },
  { log_id: 2, entity_type: 'FOUND', entity_id: 1, old_status: 'Found', new_status: 'Matched', changer_name: 'Mohul Ramjee', changer_role: 'student', change_notes: 'Automated 100-point matching engine computed 100% score.', timestamp: '2026-09-08T15:30:00Z' },
  { log_id: 3, entity_type: 'LOST', entity_id: 1, old_status: 'Lost', new_status: 'Matched', changer_name: 'Mohul Ramjee', changer_role: 'student', change_notes: 'Automated 100-point matching engine computed 100% score.', timestamp: '2026-09-08T15:30:00Z' }
];
